### PR TITLE
Add support for python 3.8

### PR DESCRIPTION
**Pull request by mikelane**
Adds support for python 3.8

### CODE REVIEW

**Comment by Tinche** [comment]
Thanks!

**Comment by avanov** [comment]
Has this been released on PyPy? The currently available pre-release still fails on 3.8

**Comment by causey** [comment]
I'm still seeing this import issue; when is it planned to be released?

**Comment by DiscreteTom** [comment]
Installing the master version from github by running `pip install git+https://github.com/Tinche/cattrs.git` can temporary fix this before the latest version is released on PyPI.

**Comment by DrLuke** [comment]
Thanks for the PR!

However, with the release of python 3.9 this approach will break again?

**Comment by mikelane** [comment]
> Thanks for the PR!
> 
> However, with the release of python 3.9 this approach will break again?

Yes, this will break in the same way for python 3.9, but I wanted to be conservative with my approach.

**Comment by Tinche** [comment]
I released 1.0.0 a few days ago with 3.8 support fwiw. We've upgraded at work to 3.8 and now I see we're a tiny bit buggy on 3.8, so a 1.0.1 release is probably incoming.

**Pull request merged**
