### PR TITLE
Add support for typing.ForwardDef

### PR DESCRIPTION
**Pull request by vodik**
Its also correct for type annotations to be strings that are evaluated at run time. Internally, Python converts them into typing.ForwardDef
objects and evals them at runtime. cattr needs to do the same thing as
well.

This also brings in compatibility for PEP 563 where deferred
evaluation becomes the default behaviour.

### CODE REVIEW

**Comment by vodik** [comment]
Yeah, so this is a change of the public API, but I don't think it can be fixed without doing that as we need to evaluate the annotations in the right namespace and currently that information isn't preserved.

This should provide a solution to both #42 and #13 (well, it will for #13, but I haven't actually fixed up the `Union` structurer just yet).

**Comment by vodik** [comment]
I've just noticed on attrs [#265](https://github.com/python-attrs/attrs/issues/265) that they added an `attr.resolve_types`.

I'm not sure if that function, or `get_type_hints` is sufficient to implement this properly as its possible to eval out a `ForwardRef`'d type, which would then still have to be manually eval'ed.

**Comment by Tinche** [comment]
Hi, thanks for looking into this. This is definitely something we'll need to handle soon. I'm not sure what the best solution is, but I suspect it's actually generating a class specific structure/unstructure function once and caching it. Then, at generation time, the types can be resolved.

**Comment by j-walker23** [comment]
@Tinche First, this library is awesome. Thanks for it.
Just wanted to ask if any help on this was needed or have you just gotten busy with other things. No rush of course, just curious. Would love to take advantage of this super cool lib!

**Comment by johnwlockwood** [comment]
This fails on:
```
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from typing import List, Optional
from cattr import structure, unstructure
import attr

@attr.s
class Boop(object):
    value: int = attr.ib()
    boop: Optional['Boop'] = attr.ib(default=None)


def main():
    b = {
        'value': 1,
        'boop': {
            'value': 2,
            'boop': {
                'value': 3,
                'boop': None,
            }
        }
    }
    boops = structure(b, Boop)
    print(boops)


if __name__ == "__main__":
    main()
```
`ValueError: Unsupported type: ForwardRef('Boop'). Register a structure hook for it.`

**Comment by jacobg** [comment]
Any update on resolving this issue?

**Comment by Tinche** [comment]
This is obsolete if you use from __future__ import annotations (i.e. deferred annotation processing as per PEP563), which we support, so closing this.

**Comment by Tinche** [comment]
Note: this is supported using `cattr.GenConverter`, which will become the default in one of the next versions.

**Pull request closed without merging**
