### PR TITLE
strip leading underscores from attributes so can be structured.

### PR DESCRIPTION
**Pull request by wakemaster39**
resolves issue #23

### CODE REVIEW

**Comment by anthrotype** [comment]
@Tinche what do you think of this?
It’s the single most annoying thing for me when working with attrs/cattrs. I often use the leading underscore for read-only attributes that are accessible via `@property` getters.

**Comment by Tinche** [comment]
Agreed, both with the original submission and your suggestion. @wakemaster39 if you can apply @anthrotype 's suggestion I will merge this in :)

**Comment by wakemaster39** [comment]
I made the change, I personally prefer startswith over [0] for readability but I am also not typically involved in performance in python.

**Comment by wakemaster39** [comment]
i did my best to make all the test pass, but I figured not adding in a # noqa for the linting error would be fine. Also I have never worked with hypothesis before so I am not sure how to add a test properly for _attribute_name.

 I'll read up on it, but I don't know if I will be able to sort it out in a reasonable time span.

**Comment by Tinche** [comment]
Thanks for this!

**Comment by DanielJoyce** [comment]
I'm still seeing this failure. Did this merge fail or never happen?

**Comment by DanielJoyce** [comment]
Looks like the merge failed and never went through.

**Pull request merged**
