### PR TITLE
Add smoke tests for nested attrs-dataclasses

### PR DESCRIPTION
**Pull request by asford**
https://github.com/Tinche/cattrs/issues/43

Minor fixes to converters.py for some basic conversion smoke tests.

### CODE REVIEW

**Comment by Tinche** [comment]
Hm I figured I would limit this functionality to the `GenConverter`, but I guess it makes sense to retrofit the legacy Converter too since that's currently used for the global converter.

**Comment by Tinche** [comment]
Which reminds me, can you parametrize these smoke tests to test both converters?

**Comment by asford** [comment]
👍 That'd be ideal for our case, as we've folks who just use the "out of box" settings for a lot of applications.

**Comment by asford** [comment]
Added parameterization, obviously feel free to slice and dice the PR as makes sense to you.

**Comment by Tinche** [comment]
Thanks!

**Pull request merged**
