### PR TITLE
Some easy optimizations

### PR DESCRIPTION
**Pull request by bluetech**
Hi,

I started using cattrs, but noticed it was slower than my previous hand-rolled code, so I added a micro-benchmark and performed some easy optimizations based on it. Please see the commit messages for details.

There are more optimizations possible of course, hopefully someone else will try :)

Also, I only looked at the dict-based code. Tuples are faster, but I use dicts for extensibility.

### CODE REVIEW

**Comment by bluetech** [comment]
Pushed a couple more commits. Travis fails because of hypothesis `FailedHealthCheck` which seems unrelated. Locally `tox` passes.

**Comment by Tinche** [comment]
Hello,

I definitely agree the next step for cattrs is working on making it very fast. I'll take a closer look in the next couple of days.

**Comment by Tinche** [comment]
I'll gladly take the benchmark example and the inlining, but I have reservations about the LRU caches. I have plans on making cattrs faster using a slightly different approach and I worry about adding too many caches at different layers. So if you could revert those I can merge this in.

I'm not saying the caches are a bad idea, I'm saying let's take this one step at a time. :)

**Comment by bluetech** [comment]
> I worry about adding too many caches at different layers.

Just to be clear - these lru caches replace already existing caches (based on dicts), they are not new caches. It's just that the lru caches are faster. Should I still remove them? (No problem if so).

(Also, I pushed another commit with a tiny simplification I just noticed).

**Comment by Tinche** [comment]
You're right, let's get this in and leave future tweaks for the future.

Thanks for your contribution :)

**Pull request merged**
