### PR TITLE
Some more small optimizations

### PR DESCRIPTION
**Pull request by bluetech**
A few more things I noticed. Please see the commit messages for details.

### CODE REVIEW

**Comment by Tinche** [comment]
Looks like a doctest is failing, please take a look :)

**Comment by bluetech** [comment]
Thanks for letting me know, looks like CI doesn't notify when it fails.

I've sent another PR #25 to deal with this failure, I'll rebase this one after #25 is accepted (or declined).

**Comment by bluetech** [comment]
Rebased on master. Added a HISTORY note.

**Comment by Tinche** [comment]
Just now gotten the chance to look at this. Looks good, thanks!

**Pull request merged**
